name: voice_maker
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter



  # Add Dependencies
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  shared_preferences: ^2.2.0
  provider: ^6.0.5
  nb_utils: ^4.4.8
  intl: ^0.18.0
  image_picker: ^0.8.7+5
  cached_network_image: ^3.1.0
  # animated_splash_screen: ^1.3.0
  google_fonts: ^4.0.1 
  video_player: ^2.7.0
  permission_handler: ^10.4.3  # For handling permissions
  file_picker: ^5.3.2 
  another_flushbar: ^1.12.30
  url_launcher: ^6.1.14
  # audio_waveforms: ^1.0.4
  # audio_wave_url_package: ^1.0.33
  audioplayers: ^5.2.0 # For playing audio
  assets_audio_player: ^3.1.1
  chat_bubbles: ^1.5.0
  just_audio: ^0.9.35
  path_provider: ^2.1.1
  fl_chart: ^0.64.0
  just_waveform: ^0.0.5
  # fl_chart: ^0.36.0 # Add the latest version

  flutter_vector_icons: ^1.0.0
  flutter_spinkit: ^5.2.0
  flutter_svg: ^1.1.4
  fluttertoast: ^8.2.2
  # flutter_sound: ^9.2.13
  flutter_downloader: ^1.11.3
  flutter_html:
  flutter_stripe: ^9.1.1
  



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - images/svgIcons/
    
  
fonts: 
    - family: Inter
      fonts: 
        - asset: fonts/InterSemiBold.ttf
          weight: 400
        - asset: fonts/InterRegular.ttf
          weight: 400
        - asset: fonts/InterMedium.ttf
          weight: 500
    - family: Raleway
      fonts: 
        - asset: fonts/RalewayRegular.ttf
          weight: 400
        - asset: fonts/RalewayMedium.ttf
          weight: 500
    - family: Montserrat
      fonts: 
        - asset: fonts/MontserratMedium.ttf
          weight: 500
    - family: Poppins
      fonts: 
        - asset: fonts/PoppinsBold.ttf
          weight: 700
        - asset: fonts/PoppinsRegular.ttf
          weight: 400
        - asset: fonts/PoppinsSemiBold.ttf
          weight: 600
        - asset: fonts/PoppinsMedium.ttf
          weight: 500
    - family: Roboto
      fonts: 
        - asset: fonts/RobotoMedium.ttf
          weight: 500
